job_environments:
  common_environment: &common_environment
    CONTAINER_PREFIX: planet4-australiapacific
    WP_DB_NAME_PREFIX: planet4-australi_wordpress
    BASE_RELEASE: v25.19.0
  develop_environment: &develop_environment
    APP_ENVIRONMENT: development
    APP_HOSTNAME: www-dev.greenpeace.org.au
    APP_HOSTPATH:
    CLOUDSQL_INSTANCE: p4-develop-k8s
    GOOGLE_PROJECT_ID: planet-4-151612
    GCLOUD_CLUSTER: p4-development
    HELM_NAMESPACE: australiapacific-development
    HELM_RELEASE: planet4-australiapacific
    WP_DB_NAME: planet4-australi_wordpress_develop
    WP_STATELESS_BUCKET: planet4-australiapacific-stateless-develop
  release_build_env: &release_build_env
    GOOGLE_PROJECT_ID: planet4-production
  release_environment: &release_environment
    APP_ENVIRONMENT: staging
    APP_HOSTNAME: www-stage.greenpeace.org.au
    APP_HOSTPATH:
    CLOUDSQL_INSTANCE: planet4-prod
    GCLOUD_CLUSTER: planet4-production
    GOOGLE_PROJECT_ID: planet4-production
    HELM_NAMESPACE: australiapacific-staging
    HELM_RELEASE: planet4-australiapacific-release
    WP_DB_NAME: planet4-australi_wordpress_release
    WP_STATELESS_BUCKET: planet4-australiapacific-stateless-release
  production_environment: &production_environment
    APP_HOSTNAME: www.greenpeace.org.au
    APP_HOSTPATH:
    CLOUDSQL_INSTANCE: planet4-prod
    GCLOUD_CLUSTER: planet4-production
    GOOGLE_PROJECT_ID: planet4-production
    HELM_NAMESPACE: australiapacific
    HELM_RELEASE: planet4-australiapacific-master
    MIN_REPLICA_COUNT: 2
    WP_DB_NAME: planet4-australi_wordpress_master
    WP_STATELESS_BUCKET: planet4-australiapacific-stateless
